#!/usr/bin/env python3
"""Show how a domain repository lines up with domain-template.

    python domains/domain-template/scripts/compare_domain.py domains/retail-wealth-management/financial-planning

Re-generates the template with the domain's own .copier-answers.yml into a temp
folder and classifies every file:

  unchanged   generated by the template, never edited
  edited      domain-owned file (copier.yml _skip_if_exists), edited in place by the domain (expected)
  DRIFTED     template-owned file that differs from the template (fix: copier update / re-render)
  added       added by the domain where the naming conventions allow
  seed-only   template seed example the domain has replaced (e.g. the lookup tool)
"""
import filecmp
import fnmatch
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
SEEDS = ("_lookup.", "_rulepack.", "nc-000-", "-api.openapi.yaml")


def files(root: Path) -> set[str]:
    skip = {".git", "build"}
    return {str(p.relative_to(root)) for p in root.rglob("*")
            if p.is_file() and not skip & set(p.relative_to(root).parts) and p.name not in (".DS_Store", "CODEOWNERS")}


def main():
    domain = Path(sys.argv[1]).resolve()
    answers = domain / ".copier-answers.yml"
    if not answers.exists():
        sys.exit(f"{domain} has no .copier-answers.yml - it was not generated from domain-template")
    with tempfile.TemporaryDirectory() as tmp:
        gen = Path(tmp) / "gen"
        subprocess.run([sys.executable, str(HERE / "scripts/new_domain.py"), "--answers", str(answers),
                        "--out", str(gen), "--no-git"], check=True, stdout=subprocess.DEVNULL)
        g, d = files(gen), files(domain)
        import yaml
        owned = (yaml.safe_load((HERE / "copier.yml").read_text()) or {}).get("_skip_if_exists", [])
        domain_owned = lambda f: any(fnmatch.fnmatch(f, pat) for pat in owned)  # noqa: E731
        rows = []
        for f in sorted(g | d):
            if f in g and f in d:
                same = filecmp.cmp(gen / f, domain / f, shallow=False)
                rows.append(("unchanged" if same else "edited" if domain_owned(f) else "DRIFTED", f))
            elif f in d:
                rows.append(("added", f))
            else:
                rows.append(("seed-only" if any(s in f for s in SEEDS) else "MISSING", f))
    width = max(len(f) for _, f in rows)
    for kind in ("unchanged", "edited", "added", "seed-only", "DRIFTED", "MISSING"):
        sel = [f for k, f in rows if k == kind]
        if sel:
            print(f"\n{kind} ({len(sel)})")
            for f in sel:
                print(f"  {f}")
    missing = [f for k, f in rows if k in ("MISSING", "DRIFTED")]
    print(f"\n{'OK' if not missing else 'NOT ALIGNED'}: {len(g)} template files, "
          f"{sum(1 for k, _ in rows if k in ('unchanged', 'edited'))} kept at the same path"
          + (f", {sum(1 for k, _ in rows if k == 'DRIFTED')} template-owned file(s) drifted" if missing else ""))
    sys.exit(1 if missing else 0)


if __name__ == "__main__":
    main()
